# Generated by Django 4.2.23 on 2025-07-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_xmsconfigurations_xis_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmsconfigurations',
            name='xis_api_key',
            field=models.CharField(help_text='Enter the XIS API Key (512 character limit)', max_length=512),
        ),
    ]
